./new-symlink.sh apps kdeconnect.svg com.github.bajoja.indicator-kdeconnect.svg
./new-symlink.sh panel laptop-connected.svg com.github.bajoja.indicator-kdeconnect.laptop-connected.svg
./new-symlink.sh panel laptop-disconnected.svg com.github.bajoja.indicator-kdeconnect.laptop-disconnected.svg
./new-symlink.sh panel laptop-trusted.svg com.github.bajoja.indicator-kdeconnect.laptop-trusted.svg
./new-symlink.sh panel laptop-connected.svg com.github.bajoja.indicator-kdeconnect.laptopconnected.svg
./new-symlink.sh panel laptop-connected.svg com.github.bajoja.indicator-kdeconnect.laptopdisconnected.svg
./new-symlink.sh panel laptopt-rusted.svg com.github.bajoja.indicator-kdeconnect.laptoptrusted.svg
./new-symlink.sh panel smartphone-connected.svg com.github.bajoja.indicator-kdeconnect.smartphone-connected.svg
./new-symlink.sh panel smartphone-disconnected.svg com.github.bajoja.indicator-kdeconnect.smartphone-disconnected.svg
./new-symlink.sh panel smartphone-trusted.svg com.github.bajoja.indicator-kdeconnect.smartphone-trusted.svg
./new-symlink.sh panel smartphone-connected.svg com.github.bajoja.indicator-kdeconnect.smartphoneconnected.svg
./new-symlink.sh panel smartphone-disconnected.svg com.github.bajoja.indicator-kdeconnect.smartphonedisconnected.svg
./new-symlink.sh panel smartphone-trusted.svg com.github.bajoja.indicator-kdeconnect.smartphonetrusted.svg
./new-symlink.sh panel tablet-connected.svg com.github.bajoja.indicator-kdeconnect.tablet-connected.svg
./new-symlink.sh panel tablet-disconnected.svg com.github.bajoja.indicator-kdeconnect.tablet-disconnected.svg
./new-symlink.sh panel tablet-trusted.svg com.github.bajoja.indicator-kdeconnect.tablet-trusted.svg
./new-symlink.sh panel tablet-connected.svg com.github.bajoja.indicator-kdeconnect.tabletconnected.svg
./new-symlink.sh panel tablet-disconnected.svg com.github.bajoja.indicator-kdeconnect.tabletdisconnected.svg
./new-symlink.sh panel tablet-trusted.svg com.github.bajoja.indicator-kdeconnect.tablettrusted.svg
