[Icon Theme]
Name=Papirus.HiDPI
Comment=A simple and modern icon theme (HiDPI workaround).
Inherits=Papirus,breeze,ubuntu-mono-dark,Mint-X,elementary,gnome,hicolor

FollowsColorScheme=true

# Directory list
Directories=22x22/panel,22x22@2x/panel,24x24/panel,24x24@2x/panel

[22x22/panel]
Context=Status
Size=22
Type=Fixed

[22x22@2x/panel]
Context=Status
Size=22
Scale=2
Type=Fixed

[24x24/panel]
Context=Status
Size=24
Type=Fixed

[24x24@2x/panel]
Context=Status
Size=24
Scale=2
Type=Fixed
