#!/bin/sh

set -e

case "$1" in
	install|upgrade)
		# Removes symbolic links before installing/upgrading the package
		#
		# The stupid way to avoid that problem in the future
		# https://github.com/PapirusDevelopmentTeam/papirus-icon-theme/issues/370
		find /usr/share/icons/ePapirus      -type l -delete > /dev/null 2>&1 || true
		find /usr/share/icons/Papirus       -type l -delete > /dev/null 2>&1 || true
		find /usr/share/icons/Papirus-Dark  -type l -delete > /dev/null 2>&1 || true
		find /usr/share/icons/Papirus-Light -type l -delete > /dev/null 2>&1 || true

		# Another stupid way to fix that issue
		# https://github.com/PapirusDevelopmentTeam/papirus-icon-theme/issues/730
		test -L /usr/share/icons/Papirus-Dark/22x22/panel \
			|| rm -rf /usr/share/icons/Papirus-Dark/22x22/panel
		test -L /usr/share/icons/Papirus-Dark/22x22/animations \
			|| rm -rf /usr/share/icons/Papirus-Dark/22x22/animations
		test -L /usr/share/icons/Papirus-Dark/24x24/panel \
			|| rm -rf /usr/share/icons/Papirus-Dark/24x24/panel
		test -L /usr/share/icons/Papirus-Dark/24x24/animations \
			|| rm -rf /usr/share/icons/Papirus-Dark/24x24/animations
		;;

	abort-upgrade)
		;;

	*)
		echo "preinst called with unknown argument \`$1'" >&2
		exit 0
		;;
esac

exit 0
